### ISSUE TITLE
Illegal reflective access operation 

### ISSUE THREAD

**Issue by sowhatifimlazy** [codieradical/MineOnline#106]
Attempting to run a [Canyon](https://github.com/canyonmodded/canyon) server w/ MineOnline so it can be listed in the server list and ran into a nasty issue:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by gg.codie.mineonline.LibraryManager (file:/home/mc_servers/canyon_modded/MineOnline.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of gg.codie.mineonline.LibraryManager
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.IllegalArgumentException: object is not an instance of declaring class
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at gg.codie.mineonline.LibraryManager.updateClasspath(LibraryManager.java:109)
        at gg.codie.mineonline.Server.main(Server.java:16)
Exception in thread "main" java.io.IOException: Error, could not add URL to system classloader
        at gg.codie.mineonline.LibraryManager.updateClasspath(LibraryManager.java:114)
        at gg.codie.mineonline.Server.main(Server.java:16)
```

**Comment by codieradical** [comment]
What version of Java are you using?

**Comment by sowhatifimlazy** [comment]
```
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7-Ubuntu-1ubuntu1)
OpenJDK 64-Bit Server VM (build 14.0.1+7-Ubuntu-1ubuntu1, mixed mode, sharing)
```

**Comment by codieradical** [comment]
This is a compatibility issue with newer Java versions. I've been working on a fix but it's not an easy problem to solve.
Different versions of Java work, I've been testing with 8 personally.
The issue has also been reported here #86 so I'm going to close this one.
