### ISSUE TITLE
Incompatible official launcher version json files seemingly cause a crash.

### ISSUE THREAD

**Issue by codieradical** [codieradical/MineOnline#107]
```
org.json.JSONException: JSONObject["downloads"] not found.
    at org.json.JSONObject.get(JSONObject.java:572)
    at org.json.JSONObject.getJSONObject(JSONObject.java:782)
    at gg.codie.mineonline.MinecraftVersion.fromLauncherVersion(MinecraftVersion.java:248)
    at gg.codie.mineonline.MinecraftVersionRepository.getVersion(MinecraftVersionRepository.java:363)
    at gg.codie.mineonline.MinecraftVersionRepository.addInstalledVersion(MinecraftVersionRepository.java:42)
    at gg.codie.mineonline.MinecraftVersionRepository.loadOfficialLauncherVersions(MinecraftVersionRepository.java:150)
    at gg.codie.mineonline.MinecraftVersionRepository.loadVersions(MinecraftVersionRepository.java:262)
    at gg.codie.mineonline.MinecraftVersionRepository.<init>(MinecraftVersionRepository.java:29)
    at gg.codie.mineonline.MinecraftVersionRepository.getSingleton(MinecraftVersionRepository.java:36)
    at gg.codie.mineonline.gui.MenuManager.main(MenuManager.java:88)
    at gg.codie.mineonline.MineOnline.main(MineOnline.java:19)
```

**Comment by codieradical** [comment]
needs reproducing.

**Comment by codieradical** [comment]
Not reproduced, I'm almost certain this is a non-issue.
