### ISSUE TITLE
discord-rpc NoClassDefFoundError

### ISSUE THREAD

**Issue by Madc30** [codieradical/MineOnline#115]
Hey, madz from SeveriaMC here. I just tried to use MineOnline but i get an error and nothing happens. This is my log

java.lang.NoClassDefFoundError: net/arikia/dev/drpc/callbacks/JoinGameCallback
	at gg.codie.mineonline.MineOnline.main(MineOnline.java:28)
Caused by: java.lang.ClassNotFoundException: net.arikia.dev.drpc.callbacks.JoinGameCallback
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

i've tried waiting and checking my .minecraft folder and i found the mineonline folder but waiting doesn't work

**Comment by codieradical** [comment]
Hi! Thanks for the report-

At first glance this looks like the sort of thing that happens when installation fails.
On first launch, MineOnline takes a moment to extract it's libraries, discord-rpc being one of them.
If something goes wrong at this time the libraries can be left corrupted.
I would recommend deleting the %AppData%\.minecraft\mineonline\lib folder, opening it again and giving it some time.

There should also be a log file at  %AppData%\.minecraft\mineonline\latest.log which would be useful.

**Comment by Madc30** [comment]
Ok, thanks!
