### ISSUE TITLE
Hosting server with MineOnline don't work

### ISSUE THREAD

**Issue by Strongleong** [codieradical/MineOnline#268]
When I run command `java -cp MineOnline.jar gg.codie.mineonline.Server (path-to-server.jar) nogui` I get following error:
`Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)
        at java.desktop/java.awt.Window.init(Window.java:496)
        at java.desktop/java.awt.Window.<init>(Window.java:448)
        at java.desktop/java.awt.Window.<init>(Window.java:603)
        at java.desktop/java.awt.Dialog.<init>(Dialog.java:664)
        at java.desktop/java.awt.Dialog.<init>(Dialog.java:509)
        at java.desktop/javax.swing.JDialog.<init>(JDialog.java:423)
        at java.desktop/javax.swing.JDialog.<init>(JDialog.java:375)
        at java.desktop/javax.swing.JDialog.<init>(JDialog.java:349)
        at gg.codie.mineonline.gui.ProgressDialog.<init>(ProgressDialog.java:36)
        at gg.codie.mineonline.gui.ProgressDialog.showProgress(ProgressDialog.java:96)
        at gg.codie.mineonline.LibraryManager.extractLibraries(LibraryManager.java:20)
        at gg.codie.mineonline.Server.main(Server.java:23)
`

**Comment by Strongleong** [comment]
I run on Debian 10

**Comment by codieradical** [comment]
This shouldn't be happening, thanks for the report.
As a temporary fix, you can try this 
export DISPLAY=:0.0

**Comment by codieradical** [comment]
Please try this test build
https://github.com/codieradical/MineOnline/releases/tag/3.6.5.1-bugfix-268

**Comment by codieradical** [comment]
By the way, you can contact me on Discord to get things faster :)
https://discord.gg/vYd89ydZ

**Comment by Strongleong** [comment]
Well... it did something. But not much

`Launching Server (path)/minecraft_server.jar
java.nio.file.NoSuchFileException: /home/(username)/.minecraft/versions
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:432)
        at java.base/java.nio.file.Files.newDirectoryStream(Files.java:471)
        at gg.codie.mineonline.MinecraftVersionRepository.getOfficialLauncherJars(MinecraftVersionRepository.java:160)
        at gg.codie.mineonline.MinecraftVersionRepository.loadOfficialLauncherVersions(MinecraftVersionRepository.java:186)
        at gg.codie.mineonline.MinecraftVersionRepository.access$100(MinecraftVersionRepository.java:17)
        at gg.codie.mineonline.MinecraftVersionRepository$1.run(MinecraftVersionRepository.java:407)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at gg.codie.minecraft.server.MinecraftServerProperties.<init>(MinecraftServerProperties.java:31)
        at gg.codie.mineonline.server.MineOnlineServerProperties.<init>(MineOnlineServerProperties.java:18)
        at gg.codie.mineonline.server.MinecraftServerProcess.main(MinecraftServerProcess.java:73)
`

Will try make script by my own

**Comment by codieradical** [comment]
ok funky, just make that folder

**Comment by codieradical** [comment]
new test build for you, this should resolve that issue
https://github.com/codieradical/MineOnline/releases/tag/3.6.5.2-bugfix-268

**Comment by Strongleong** [comment]
Something new again
Launching Server (path)/minecraft_server.jar
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at gg.codie.minecraft.server.MinecraftServerProperties.<init>(MinecraftServerProperties.java:31)
        at gg.codie.mineonline.server.MineOnlineServerProperties.<init>(MineOnlineServerProperties.java:18)
        at gg.codie.mineonline.server.MinecraftServerProcess.main(MinecraftServerProcess.java:73)

**Comment by codieradical** [comment]
probably can't find server.properties, try making that file, i'll fix this also

**Comment by codieradical** [comment]
Isseus resolved for next release.
