### ISSUE TITLE
LibraryManager compatibility for newer Java versions.

### ISSUE THREAD

**Issue by arceuss** [codieradical/MineOnline#86]
`debian@vps-d4eb3803:~/b173$ java -cp MineOnline.jar gg.codie.mineonline.Server minecraft_server.jar -Xmx1024M -Xms1024M -jar minecraft_server.jar nogui
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by gg.codie.mineonline.LibraryManager (file:/home/debian/b173/MineOnline.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of gg.codie.mineonline.LibraryManager
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.IllegalArgumentException: object is not an instance of declaring class
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at gg.codie.mineonline.LibraryManager.updateClasspath(LibraryManager.java:65)
        at gg.codie.mineonline.Server.main(Server.java:23)
Exception in thread "main" java.io.IOException: Error, could not add URL to system classloader
        at gg.codie.mineonline.LibraryManager.updateClasspath(LibraryManager.java:70)
        at gg.codie.mineonline.Server.main(Server.java:23)`

**Comment by codieradical** [comment]
Thanks for this!
I'll address this in an update, for now I'm testing on Java 8.

**Comment by arceuss** [comment]
thank you

**Comment by codieradical** [comment]
Resolved as of 2.5.0-Pre2
https://github.com/codieradical/MineOnline-API/releases/tag/2.5.0-pre2
